language: perl
before_install:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
  - cpanm --quiet --notest --skip-satisfied --installdeps --with-recommend .
  - cover -delete
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
matrix:
  include:
    - perl: "5.30"
    - perl: "5.28"
    - perl: "5.26"
    - perl: "5.24"
    - perl: "5.22"
    - perl: "5.20"
    - perl: "5.18"
    - perl: "5.16"
    - perl: "5.14"
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
